# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= darwin14.1.0
MACHINETYPE	:= x86_64
PLATFORM	:= x86_64-apple-darwin14.1.0
FULLOSTYPE	:= apple-darwin14.1.0
