# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= darwin14.1.0
MACHINETYPE	:= i386
PLATFORM	:= i386-apple-darwin14.1.0
FULLOSTYPE	:= apple-darwin14.1.0
